# Generated by Django 3.2.5 on 2021-07-22 06:19

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(help_text='Введите должность', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(help_text='Введите фамилию', max_length=20)),
                ('first_name', models.CharField(help_text='Введите имя', max_length=20)),
                ('middle_name', models.CharField(help_text='Введите отчество', max_length=20)),
                ('telegram_nickname', models.CharField(help_text='Введите никнейм Telegram', max_length=20, unique=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='Введите номер телефона', max_length=14, region=None, unique=True)),
                ('personal_email', models.EmailField(help_text='Введите персональный email', max_length=50, unique=True)),
                ('work_email', models.EmailField(help_text='Введите рабочий email', max_length=50, unique=True)),
                ('employment_date', models.DateField(help_text='Введите дату приёма на работу')),
                ('date_of_birth', models.DateField(help_text='Введите дату рождения')),
                ('rank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.rank')),
            ],
        ),
    ]
