# Generated by Django 3.2.5 on 2021-07-22 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rank',
            options={'verbose_name': 'Rank'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'Staff'},
        ),
    ]
