# Generated by Django 3.2.5 on 2021-07-22 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20210722_1027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rank',
            options={'verbose_name': 'Rank', 'verbose_name_plural': 'Rank'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'Staff', 'verbose_name_plural': 'Staff'},
        ),
    ]
