# Generated by Django 3.2.5 on 2021-07-22 13:38

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20210722_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('rank', models.CharField(max_length=20)),
                ('telegram_nickname', models.CharField(max_length=20, unique=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=14, region=None)),
                ('personal_email', models.EmailField(max_length=50, unique=True)),
                ('work_email', models.EmailField(max_length=50, unique=True)),
                ('employment_date', models.DateField()),
                ('date_of_birth', models.DateField()),
                ('date_of_dismissal', models.DateField()),
            ],
            options={
                'verbose_name': 'Staff Archive',
                'verbose_name_plural': 'Staff Archive',
            },
        ),
    ]
