# Generated by Django 3.2.5 on 2021-07-23 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasksArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Тема сообщения', max_length=150)),
                ('content', models.TextField(help_text='Текст сообщения')),
                ('result', models.TextField(blank=True, help_text='Результат', null=True)),
                ('sender', models.CharField(max_length=100)),
                ('addressee', models.CharField(max_length=100)),
                ('send_datetime', models.DateTimeField(help_text='Дата сообщения')),
                ('closed', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Tasks Archive',
                'verbose_name_plural': 'Tasks Archive',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Тема сообщения', max_length=150)),
                ('content', models.TextField(help_text='Текст сообщения')),
                ('result', models.TextField(blank=True, help_text='Результат', null=True)),
                ('send_datetime', models.DateTimeField(help_text='Дата сообщения')),
                ('closed', models.BooleanField()),
                ('addressee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addressee', to='staff.staff')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
