# Generated by Django 3.2.5 on 2021-07-23 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='send_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='Дата сообщения'),
        ),
    ]
