# Generated by Django 3.2.5 on 2021-07-22 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20210722_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='addressee_id',
            new_name='addressee',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='sender_id',
            new_name='sender',
        ),
    ]
