# Generated by Django 3.2.5 on 2021-07-22 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20210722_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='addressee',
            new_name='addressee_id',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='sender',
            new_name='sender_id',
        ),
    ]
