# Generated by Django 3.2.5 on 2021-07-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_tasks_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasksArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Тема сообщения', max_length=150)),
                ('content', models.TextField(help_text='Текст сообщения')),
                ('result', models.TextField(blank=True, help_text='Результат', null=True)),
                ('sender', models.CharField(max_length=100)),
                ('addressee', models.CharField(max_length=100)),
                ('send_datetime', models.DateTimeField(help_text='Дата сообщения')),
                ('closed', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Tasks Archive',
                'verbose_name_plural': 'Tasks Archive',
            },
        ),
        migrations.AlterField(
            model_name='tasks',
            name='result',
            field=models.TextField(blank=True, help_text='Результат', null=True),
        ),
    ]
